version: "3.7"
services:
  db:
    image: postgres:12.13-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\Users\bohdank\Personal\slg\postgres_data